version: '3'

services:
  db:
    image: mysql
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - db
  code:
    build: .
    volumes:
      - .:/venv
    ports:
      - "5000:5000"
    depends_on:
      - db
      - nginx
    command: python seed.py python run.py runserver 0.0.0.0:8000
