default: &default
  adapter: mysql
  encoding: unicode
  host: localhost
  username: admin
  password: admin
  pool: 5

development:
  <<: *default
  database: framgiatw

test:
  <<: *default
  database: framgiatw
